version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: algoritmo_humano_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: reinaldo
      POSTGRES_PASSWORD: algoritmohumano
      POSTGRES_DB: algoritmo_humano
    volumes:
      - algoritmo:/var/lib/postgresql/data

volumes:
  algoritmo:
